CREATE TABLE IF NOT EXISTS SETTLED_TRANSACTIONS (
    TRANSACTION_ID TEXT PRIMARY KEY,
    DATE TEXT,
    OUTFLOW INTEGER,
    INFLOW INTEGER,
    CATEGORY TEXT,
    ACCOUNT TEXT,
    REFERENCE TEXT,
    STATUS TEXT
    );