services:
  budget_automation:
      image: ghcr.io/mojarsh/budget-automation:latest
      container_name: budget_automation
      env_file:
        - ${CREDS_DIR:-.}/.env
      volumes:
        - ${BASE_DIR}/config/category_mapping.json:/app/config/category_mapping.json:ro
        - ${GOOGLE_CREDS_PATH:-./google_creds.json}:/app/google_creds.json:ro
        - ${BASE_DIR:-./logs}/logs/budget_automation.log:/app/budget_automation.log
      profiles:
        - run
      networks:
        - postgres-shared

networks:
  postgres-shared:
    external: true
